export const skills = [
  {
    id: 1,
    title: "HTML 5",
    // src: "https://img.icons8.com/ios/50/000000/html-5--v2.png",
    src: "https://img.icons8.com/color/50/000000/html-5.png",
  },
  {
    id: 2,
    title: "CSS 3",
    src: "https://img.icons8.com/color/48/000000/css3.png",
  },
  {
    id: 3,
    title: "Javascript",
    src: "https://img.icons8.com/color/48/000000/javascript.png",
  },
  {
    id: 4,
    title: "React JS",
    src: "https://img.icons8.com/color/48/000000/react-native.png",
  },
  {
    id: 5,
    title: "Node JS",
    src: "https://img.icons8.com/color/48/000000/nodejs.png",
  },
  {
    id: 6,
    title: "Mongo DB",
    src: "https://img.icons8.com/color/48/000000/mongodb.png",
  },
  {
    id: 7,
    title: "Java",
    src: "https://img.icons8.com/color/48/000000/java-coffee-cup-logo.png",
  },
  {
    id: 8,
    title: "SQL",
    src: "https://img.icons8.com/color/48/000000/sql.png",
  },
  {
    id: 9,
    title: "GIT",
    src: "https://img.icons8.com/color/48/000000/git.png",
  },
  {
    id: 10,
    title: "C #",
    src: "https://img.icons8.com/color/48/000000/c-sharp-logo.png",
  },
  {
    id: 11,
    title: "PHP",
    src: "https://img.icons8.com/color/48/000000/php.png",
  },
  {
    id: 12,
    title: "Flutter",
    src: "https://img.icons8.com/color/48/000000/flutter.png",
  },
  {
    id: 13,
    title: "REST API",
    src: "https://img.icons8.com/color/48/000000/api-settings.png",
  },
  {
    id: 14,
    title: "Firebase",
    src: "https://img.icons8.com/color/48/000000/firebase.png",
  },
  {
    id: 15,
    title: "Material UI",
    src: "https://img.icons8.com/color/48/000000/material-ui.png",
  },
];

export const projects = [
  {
    id: 97,
    name: "Blog Book",
    img: "/images/crypto.jpg",
    desc: "Express yourself and read other people ideas",
    tags: ["React", "Typescript", "Reactstrap", "Node", "Express", "Mongo DB"],
    link: "https://blogbookblogs.netlify.app/",
    src: "https://github.com/joycendc",
  },
  {
    id: 98,
    name: "Cryptoworld",
    img: "/images/crypto.jpg",
    desc: "View Top Cryptocurrencies around the world and see their latest information and Get updates for Cryptocurrency news",
    tags: ["React JS", "Ant d", "API"],
    link: "https://crypto-worldsite.netlify.app/",
    src: "https://github.com/joycendc",
  },
  {
    id: 99,
    name: "Rick and Morty Characters",
    img: "/images/rnm.jpg",
    desc: "Shows All Rick and Morty Characters usinng Rick and Morty API and React Query",
    tags: ["React JS", "React Query", "API"],
    link: "https://rick-and-morty-characterslist.netlify.app/",
    src: "https://github.com/joycendc",
  },
  {
    id: 1,
    name: "Gagol Search",
    img: "/images/gagol.jpg",
    desc: "Have a question ? Just gagol search it to get answers and informations",
    tags: ["React JS", "Chakra UI", "Material UI", "API"],
    link: "https://gagolsearch.netlify.app/",
    src: "https://github.com/joycendc",
  },
  {
    id: 2,
    name: "All About Rizal",
    img: "/images/rizal.jpg",
    desc: "This site contains very comprehensive materials on and by Rizal in both the English and Filipino languages and continues to acquire and update information",
    tags: ["HTML", "CSS", "JS"],
    link: "https://all-about-rizal.netlify.app/",
    src: "https://github.com/joycendc",
  },
  {
    id: 3,
    name: "Charants",
    img: "/images/rant.jpg",
    desc: "This app let you post your rants about your life",
    tags: ["HTML", "CSS", "JS"],
    link: "https://charants.netlify.app/",
    src: "",
  },
  {
    id: 5,
    name: "Me Ecommerce",
    img: "/images/ecom.jpg",
    desc: "Simple Ecommerce website",
    tags: ["HTML", "CSS", "JS"],
    link: "https://me-ecommerce.netlify.app/",
    src: "",
  },
  {
    id: 6,
    name: "Chararat",
    img: "/images/charat.jpg",
    desc: "Simple Chatting app using Chat Engine",
    tags: ["React", "Chat Engine", "MUI"],
    link: "https://chararat.netlify.app/",
    src: "",
  },
  {
    id: 7,
    name: "Chat App",
    img: "/images/chat.jpg",
    desc: "Simple chat app using Socket IO",
    tags: ["React JS", "Socket IO"],
    link: "https://chat-app-testing.netlify.app/",
    src: "",
  },
  {
    id: 8,
    name: "Library Mangement System",
    img: "/images/lms.png",
    desc: "Library Management System built on Netbeans IDE",
    tags: ["Java", "My SQL"],
    link: "",
    src: "https://github.com/joycendc/Java-LibrarayManagementSystem",
  },
  {
    id: 9,
    name: "ATM Simulator",
    img: "/images/thumb.jpg",
    desc: "ATM Simulator built in Neatbeans IDE",
    tags: ["Java", "My SQL"],
    link: "",
    src: "https://github.com/joycendc/Java-ATM",
  },
  {
    id: 10,
    name: "Payroll Management System",
    img: "/images/pms.png",
    desc: "Payroll Managment System website using ASP.Net and C#",
    tags: ["Asp.NET", "C#", "SQL"],
    link: "",
    src: "https://github.com/joycendc/Java-ATM",
  },
];
